name: Build SCI-G Examples

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the geometry and plugins, install them in systemsTxtDB
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc3:dev-fedora36
    name: Build ${{ matrix.example }}
    strategy:
      fail-fast: false
      matrix:
        example:
          - examples/basic_materials
          - examples/cad_imports
          - examples/dosimeter
          - examples/flux_detector
          - examples/scintillator_array
          - examples/sqlite_db
          - examples/variations

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build geo
        run: |
          ./ci/build.sh -e ${{ matrix.example }}
      - uses: gitboard-io/gitboard-action@main
        with:
          username: maureeungaro
          key: 3d8e9059-a164-4bea-9541-1cb8789d805b
 
