name: Build SCI-G Examples

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the geometry and plugins, install them in systemsTxtDB
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc3:1.0
    name: Build ${{ matrix.example }}
    strategy:
      fail-fast: false
      matrix:
        example:
          - examples/simple_flux
          - examples/dosimeter
          - examples/scintillator_array
          - examples/materials

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build geo
        run: |
          ./ci/build.sh -e ${{ matrix.example }}

 
